name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run FunctionalPlaywright tests
      run: npx playwright test --grep-invert "@a11y|@visual"
      env: 
        PLAYWRIGHT_HTML_REPORT: blob-report-functional
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
    - name: Run Non Functional tests
      run: npx playwright test --grep "@a11y|@visual"
      continue-on-error: true
      env: 
        PLAYWRIGHT_HTML_REPORT: blob-report-non-functional
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
    - name: Merge Playwright Reports
      if: ${{ !cancelled() }}
      run: npx playwright merge-reports --reported=html blob-report-functional blob-report-non-functional
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload GitHub Pages Artifact
      uses: actions/upload-pages-artifact@v3
      if: ${{ !cancelled() }}
      with:
        path: playwright-report/

  deploy-report:
    needs: test
    if: "!cancelled() && github.ref == 'refs/heads/main'"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
